### ISSUE TITLE
Link to manual is broken

### ISSUE THREAD

**Issue by ioquatix** [kiibohd/controller#288]
https://input.club/k-type/

The link to the manual is 404.

**Comment by voronoipotato** [comment]
lmao, JUNE.

**Comment by ioquatix** [comment]
Yeah, is anything here maintained?

**Comment by haata** [comment]
Fixed!
Sorry about that.

**Comment by voronoipotato** [comment]
Documentation is really important  . I know _everything_ can feel important when you're trying to run all of it on your own, but maybe delegate a little to community members where you can if you're having trouble with documentation. I'm currently using one of your keyboards, they're great! When your users don't have access to documentation though they're more likely to travel down an unhappy path and report an issue, perhaps even an issue that doesn't actually exist. They just misunderstood the expected behavior.
