### ISSUE TITLE
Kira LED faults

### ISSUE THREAD

**Issue by donfuldauer** [kiibohd/controller#307]
* **Device**:
Kira

* **Firmware Origin**:
Kiibohd Configurator 1.0.0

* **OS**:
Windows 10 Pro v1809 OS build 17763.253

* **Reproduction Steps**:
Power on board and let run some unknown amount of time (has occurred multiple times anywhere from 1 to 4 hours from what I can tell)

* **Resulting Issue**:
Sections of LEDs will either be off, stuck red, or flickering with a visible refresh rate. Only way to recover is to reset the board. Reproduced multiple times, each time with different behaviors. Has occurred with both a fixed color set and while running an animation.

Example of fault after running Kira Wave for awhile: [https://imgur.com/a/VkYeGoY](https://imgur.com/a/VkYeGoY)

Edit (HaaTa): Fixed the markdown link

**Comment by haata** [comment]
I have seen this issue myself (multiple times). I'm not entirely sure what causes it yet and I'm not sure whether it's within the ISSI chip (LED driver) or within the MCU.

My suspicion is that some USB interrupt is interfering and causing some i2c communication to get corrupted. But since this bug seems to never happen when I have monitoring tools on...ugh.

I've seen this issue happen multiples times in a day, but then not happen for weeks.

**Comment by kevinpoitra** [comment]
I ran into the same issue as well, but I don't seem to be able to fully reset the LEDs on my keyboard. I decided to capture a few videos of the issue to help demonstrate.

I received my Kira today, and had only made one configuration change thus far: I set the startup animation to 'rainbow_wave'. All was fine until about ten hours later. As I was typing, the LED animation suddenly switched, as seen in [this video](https://www.youtube.com/watch?v=DcGxENGVVIQ).

I then reset the keyboard via RCTRL + RShift + ESC, and [this happened](https://www.youtube.com/watch?v=KxYboiU9YwU) - the bottom row of keys will only show red, keys in the numpad area flicker between colors, and the caps/num/scroll lock LED indicators aren't just white and are seemingly affected by the animation or flickering issues.

I then [switched the startup animation to kira_wave](https://www.youtube.com/watch?v=2KmoMWw7WJQ), which shows the color and flickering issues more clearly.

**Comment by haata** [comment]
This issue should be resolved with https://github.com/kiibohd/controller/commit/e94a6562cc8e1a8cb63fe9ee65c5f801fadbe521

I'm targeting a release by the end of the week, though for anyone that doesn't mind compiling the firmware themselves, it should be working now.

**Comment by kevinpoitra** [comment]
Just flashed my keyboard with freshly compiled firmware from the latest master, will report back here if any issues arise.

**Comment by haata** [comment]
We're also working on a guide to fix the LEDs in harsh RF environments (i.e. do you have a 2 watt transmitter on your desk next to your keyboard?). Will involve adding a ferrite choke to the inside of the keyboard, but it seems to help a lot.

**Comment by kevinpoitra** [comment]
Well, about 20 hours passed since I flashed the new firmware, and all was fine up until a minute ago. Now, kira_wave is stuck on a single frame - no incorrect colors, just no animation. Is there any way for me to verify that the firmware on the keyboard is what I compiled?

Also, although I hadn't touched anything after flashing, would flashing the firmware after making any setting change within the configurator apply those setting changes to the firmware on the keyboard, or to a copy of the latest official release (as in, would I overwrite my custom compiled firmware with officially released firmware by changing settings)?

As for transmitters, I don't have anything like that nearby. My wireless equipment consists of a router (which is about five feet away), and my phone with its wireless charger (2 or 3 feet away from the keyboard).

**Comment by haata** [comment]
No, flashing from the custom firmware will overwrite all the settings you did in the configurator (but you can flash with the configurator and it will go back to what you had).

The 0.5.4 release is looking good, I believe I only have one more fix left until I can start preparing the release.

**Comment by haata** [comment]
I'm going to mark this fixed for now. Will revisit again if there are still issues after v0.5.4 is released.
