### ISSUE TITLE
Kira OS input misbehavior after flash

### ISSUE THREAD

**Issue by donfuldauer** [kiibohd/controller#308]
* **Device**:
Kira

* **Firmware Origin**:
Kiibohd Configurator 1.0.0

* **OS**:
Windows 10 Pro v1809 OS build 17763.253

* **Reproduction Steps**:
Flash firmware from the Configurator after resetting the board into the bootloader via keyboard macro.

* **Resulting Issue**:
Mouse left-click appears to behave like a click-hold and drag, likely related to shift key. Windows key does not work. Issue appears to eventually go away on its own or can be resolved by restarting Windows. Does not appear to be an issue when resetting into bootloader via button.

**Comment by jamiehs** [comment]
I was having this issue as well; it's also [mentioned in the firmware released last weekend](https://kiibohd.github.io/wiki/#/Keyboards/Kira?id=fixed-issues). The Shift and Alt keys remain pressed because Windows never heard a "keyup" event (I'm a JavaScript guy so I might not have the terminology right).

The fix is to tap the right Shift and Alt keys after flashing. Essentially, tap all your gray modifiers (left and right side) and it goes away (my experience).

**Comment by haata** [comment]
This was fixed in https://github.com/kiibohd/controller/commit/3677a990eedb63302298a7de1c0bda4f115d5966

After the first update, this should no longer be an issue (you may need to reboot your computer).

Here's the "official" Microsoft guidance on the issue: https://support.microsoft.com/en-us/help/3070736/keyboard-doesn-t-work-right-after-unplug-or-undock-and-then-reconnecti

**Comment by haata** [comment]
Now fixed.
